### PR TITLE
Revert "docker-1"

### PR DESCRIPTION
**Pull request by gao-ti**
Reverts trilogy-group/tu2k22-zhiyuangao-trial#2

### CODE REVIEW

**Comment by sirjan-cn** [comment]
why deleting the server code?

**Comment by gao-ti** [comment]
image

**Comment by kushal-ti** [comment]
why are you using force push for the commits?

**Comment by gao-ti** [comment]
@kushal-ti force push was needed to squash the commits into one. This PR doesn't involve others so I think it's appropriate xd

**Review by sirjan-cn — APPROVED** [review]

**Pull request merged**
